export async function openIMessageAndPasteImage(contacts?: string[]) {
  let contactsAppleScriptBlock;
  if (contacts && contacts.length > 0)
    contactsAppleScriptBlock = contacts
      .filter((c) => c.toLowerCase() !== 'you')
      .map((contact) => {
        return `
        keystroke "${contact}"  -- input the phone number
        delay 0.1 -- this is super critical, it seems without the delay it wont work
        key code 36 —- enter
        delay 0.1 -- this is super critical, it seems without the delay it wont work`;
      });

  try {
    const script = `
          osascript -e  'activate application "Messages"
              delay 0.1 -- this is super critical, it seems without the delay it wont work
              tell application "System Events" to tell process "Messages"
              delay 0.1 -- this is super critical, it seems without the delay it wont work
              key code 45 using command down           -- press Command + N to start a new window
              delay 0.1 -- this is super critical, it seems without the delay it wont work
      
              ${
                contactsAppleScriptBlock
                  ? contactsAppleScriptBlock.join('\n')
                  : ''
              }
      
              key code 48 -- tab
              delay 0.1 -- this is super critical, it seems without the delay it wont work
              keystroke "v" using command down
              delay 0.1 -- this is super critical, it seems without the delay it wont work
              keystroke "Generated by Textualize [https://jweinstein2.github.io/textualize_web]"  -- input the message
          end tell'
          `;
    await window.ipcRenderer.invoke("run-applescript", script);
  } catch (e) {
    // eslint-disable-next-line no-alert
    alert('Something went wrong. Open iMessage yourself to send');
  }
}
