name: Build

on:
    push:
        branches: [main]
        paths-ignore:
            - "**.md"
            - "**.spec.js"
            - ".idea"
            - ".vscode"
            - ".dockerignore"
            - "Dockerfile"
            - ".gitignore"
            - ".github/**"
            - "!.github/workflows/build.yml"

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Python executable
              uses: sayyid5416/pyinstaller@v1
              with:
                  python_ver: "3.11"
                  spec: "backend/api.py"
                  requirements: "backend/requirements.txt"
                  python_arch: "arch"
                  exe_path: "./dist-python"
                  options: --onedir, --name "My App", --windowed,

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Build Release Files
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  APPLEID: ${{ secrets.APPLEID }}
                  APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
                  TEAMID: ${{ secrets.TEAMID }}

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: release_on_${{ matrix. os }}
                  path: release/
                  retention-days: 5
